package tests;

import dto.Workout;

public class WorkoutFactory {

    private final static String WORKOUT_NAME = "Test Workout";

    public static Workout get(String workoutType) {
        if (workoutType.equals("Run")) {
            return Workout.builder()
                    .workoutType(workoutType)
                    .workoutDate("11/07/2022")
                    .workoutTime("06:00 AM")
                    .workoutName(WORKOUT_NAME)
                    .description("BLABLA")
                    .plannedDuration("01:12:12")
                    .plannedDistance("10")
                    .plannedDistanceType("km")
                    .distance("10")
                    .distanceType("km")
                    .duration("01:20:00")
                    .paceType("km")
                    .overallPlace("10")
                    .ageGroupPlace("30")
                    .radioButtonName("Good")
                    .perceivedEffort("1")
                    .minHR("80")
                    .avgHR("100")
                    .maxHR("120")
                    .burnedkCal("1000")
                    .postWorkoutNotesResults("Some notes")
                    .temperature("25")
                    .temperatureType("C")
                    .humidity("60")
                    .comments("Some comments")
                    .build();
        } else if (workoutType.equals("Bike")) {
            return Workout.builder()
                    .workoutType(workoutType)
                    .workoutDate("11/07/2022")
                    .workoutTime("06:00 AM")
                    .workoutName(WORKOUT_NAME)
                    .description("BLABLA")
                    .plannedDuration("01:12:12")
                    .plannedDistance("10")
                    .plannedDistanceType("km")
                    .distance("10")
                    .distanceType("km")
                    .duration("01:20:00")
                    .paceType("mp")
                    .overallPlace("1")
                    .ageGroupPlace("30")
                    .elevationGain("1000")
                    .elevationGainType("me")
                    .elevationLoss("700")
                    .elevationLossType("ft")
                    .radioButtonName("Poor")
                    .perceivedEffort("1")
                    .avgPower("100")
                    .maxPower("120")
                    .avgCadence("60")
                    .maxCadence("80")
                    .minHR("80")
                    .avgHR("100")
                    .maxHR("120")
                    .burnedkCal("1000")
                    .postWorkoutNotesResults("Some notes")
                    .temperature("25")
                    .temperatureType("C")
                    .humidity("60")
                    .comments("Some comments")
                    .build();

        } else {
            return Workout.builder()
                    .workoutType(workoutType)
                    .workoutDate("11/07/2022")
                    .workoutTime("06:00 AM")
                    .workoutName(WORKOUT_NAME)
                    .description("BLABLA")
                    .plannedDuration("01:12:12")
                    .plannedDistance("10")
                    .plannedDistanceType("km")
                    .distance("10")
                    .distanceType("km")
                    .duration("01:20:00")
                    .paceType("mp")
                    .elevationGain("1000")
                    .elevationGainType("me")
                    .elevationLoss("700")
                    .elevationLossType("ft")
                    .radioButtonName("Poor")
                    .perceivedEffort("1")
                    .avgPower("100")
                    .maxPower("120")
                    .avgCadence("60")
                    .maxCadence("80")
                    .minHR("80")
                    .avgHR("100")
                    .maxHR("120")
                    .burnedkCal("1000")
                    .postWorkoutNotesResults("Some notes")
                    .temperature("25")
                    .temperatureType("F")
                    .humidity("60")
                    .comments("Some comments")
                    .build();
        }
    }
}

